SELECT ITEM_ID, ITEM_NAME, RARITY

FROM ITEM_INFO

WHERE ITEM_ID IN (

    SELECT t.ITEM_ID
    FROM ITEM_INFO AS i
    JOIN ITEM_TREE AS t ON i.ITEM_ID = t.PARENT_ITEM_ID
    WHERE i.RARITY = 'RARE'
)

ORDER BY ITEM_ID DESC;